services:
  hogwarts-artifact-online:
    image: hogwarts-artifact-online:1.0
    ports:
      - 8080:8080

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - hogwarts-artifact-online

  grafana:
    image: grafana/grafana-enterprise
    volumes:
      - ./docker/grafana:/var/lib/grafana
    env_file:
      - ./docker/grafana/grafana-config.env
    ports:
      - 3000:3000
  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    ports:
      - 8025:8025 # UI port
      - 1025:1025 # SMTP port
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411