spring:
  cloud:
    azure:
      keyvault:
        secret:
          property-sources[0]:
            endpoint: ${AZURE_KEY_VAULT_ENDPOINT} # environment variable
  datasource:
    url: ${datasource-url} #  secret from Azure Key Vault
    username: ${datasource-username} # secret from Azure Key Vault
    password: ${datasource-password} # secret from Azure Key Vault
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  flyway:
    locations: classpath:db/migration/mysql

api:
  endpoint:
    base-url: /api/v1

server:
  port: 80
