CREATE TABLE hogwarts_user (
  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   username VARCHAR(255),
   password VARCHAR(255),
   enable BOOLEAN NOT NULL,
   roles VARCHAR(255),
   CONSTRAINT pk_hogwartsuser PRIMARY KEY (id)
);